### PR TITLE
Updated for 64-bit AS numbers

### PR DESCRIPTION
**Pull request by mwfarb**
- Increase size of html AS inputs.
- Use human-readable ASes for display.
- Reformat AS inputs on submission to human-readable.
- Ability to auto-size AS node width to accommodate long ASes.
- Revert to reliable IA strings.
- Ability to truncate AS names and show tooltips.
- Updated GUI and command-line processes.
- Adding test scenario topology configurations.
- Updated IA regular expressions.
- Fixed bad link type when segments are missing.
- Fixed up and core segment order in display lists.
- Fixed ISD color choice to avoid duplicates.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-viz/45)

### CODE REVIEW

**Comment by perrig** [comment]
Hi Mike,

Option 3 looks good. Ideally, each AS would have a short human-readable
name, then that could be displayed and the entire AS number when the mouse
hovers over it.

All the best,
  Adrian

**Comment by kormat** [comment]
Hey. Please note that we settled on a shorter AS notation: https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering, as of https://github.com/scionproto/scion/pull/1515.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-:-LAwNL8VCkw_2auIG_Cw:b-qvmzan)*

**Comment by jonghoonkwon** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[python/as_viewer.py, line 110 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxMo5uETDtYMp9Cyun:-LAxMo5uETDtYMp9Cyuo:bmd4209) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/as_viewer.py#L110)):*
> ```Python
>         ia = str(s_isd_as).split("-")
>         conf_dir = "%s/%s/ISD%s/AS%s/endhost" % (
>             SCION_ROOT, GEN_PATH, ia[0], ia[1])
> ```

You can directly use the `ISD_AS` methods.
For example, `s_isd_as[0], s_isd_as[1]`

---

*[python/as_viewer.py, line 151 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxO12J0td_TjqVbUwx:-LAxO12J0td_TjqVbUwy:b-3cz4ey) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/as_viewer.py#L151)):*
> ```Python
>     cmd = 'cd %s && python/bin/sciond --api-addr /run/shm/sciond/sd%s.sock sd%s \
>         gen/ISD%s/AS%s/endhost' % (
>         SCION_ROOT, s_isd_as, s_isd_as, ia[0], ia[1])
> ```

Same above.

---

*[python/web/asviz/views.py, line 128 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxPfmj1feYP1zh7Tt4:-LAxPfmj1feYP1zh7Tt5:buo9nmt) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L128)):*
> ```Python
>             core.append({
>                 "ISD": ia[0],
>                 "AS": ia[1],
> ```

Same here

---

*[python/web/asviz/views.py, line 166 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxPh-49YYQd5sejB0X:-LAxPh-49YYQd5sejB0Y:buo9nmt) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L166)):*
> ```Python
>             core.append({
>                 "ISD": ia[0],
>                 "AS": ia[1],
> ```

Same here

---

*[python/web/asviz/views.py, line 727 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxQ54o80BYcnHDjV1r:-LAxQ54o80BYcnHDjV1s:buo9nmt) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L727)):*
> ```Python
>     cmd = 'cd %s && python/bin/sciond --api-addr /run/shm/sciond/sd%s.sock \
>         sd%s gen/ISD%s/AS%s/endhost' % (
>         SCION_ROOT, s_isd_as, s_isd_as, ia[0], ia[1])
> ```

Same here

---

*[python/web/asviz/views.py, line 821 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxQ6wHDR9q9bvhWaKG:-LAxQ6wHDR9q9bvhWaKH:buo9nmt) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L821)):*
> ```Python
>             ia = str(s_isd_as).split("-")
>             conf_dir = "%s/%s/ISD%s/AS%s/endhost" % (
>                 SCION_ROOT, GEN_PATH, ia[0], ia[1])
> ```

Same here

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-viz/45)*

**Comment by mwfarb** [comment]
Adding updated screenshot.

screenshot from 2018-04-30 14-25-06

**Comment by mwfarb** [comment]
Review status: 9 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[python/as_viewer.py, line 110 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxMo5uETDtYMp9Cyun:-LBMpQzj4b8xQYRXy5iC:bgxychm) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/as_viewer.py#L110)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

You can directly use the `ISD_AS` methods.
For example, `s_isd_as[0], s_isd_as[1]`
</blockquote></details>

The same code base scion-viz/master is being used for pre and post 64-bit AS formats, scion/master and netsec-scion/scionlab, a breaking change. I could create a small branch with the proper cut-outs, but it seems like the management of getting scionlab's scion-viz on a new branch might outweigh a backward-compatible method.

`s_isd_as[1]` produces a badly formatted AS for machine/human consumption post-64-bit, and `s_isd_as.as_file_fmt()` isn't available pre-64-bit format.  For now, I created `parse_isdas()` to accommodate backward compatibility, as well as use newly formatted AS methods for human and machine readable use cases.

---

*[python/as_viewer.py, line 151 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxO12J0td_TjqVbUwx:-LBMucIl0H9sZN3SEw36:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/as_viewer.py#L151)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Same above.
</blockquote></details>

Done.

---

*[python/web/asviz/views.py, line 128 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxPfmj1feYP1zh7Tt4:-LBMudBj0pYJ1lSCVDV0:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L128)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[python/web/asviz/views.py, line 166 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxPh-49YYQd5sejB0X:-LBMudkA6LF_vTJiA2ZK:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L166)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[python/web/asviz/views.py, line 727 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxQ54o80BYcnHDjV1r:-LBMueQfE-PeTw7dJd_0:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L727)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---

*[python/web/asviz/views.py, line 821 at r1](https://reviewable.io/reviews/netsec-ethz/scion-viz/45#-LAxQ6wHDR9q9bvhWaKG:-LBMufAW2vUJSa_q_c-9:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/5fadf2fab00e02e64f1c5763d405e845aedaa189/python/web/asviz/views.py#L821)):*
<details><summary><i>Previously, jonghoonkwon wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-viz/45)*

**Pull request merged**
