### PR TITLE
Improve paths tab size and layout (old fork)

### LINKED ISSUE #27: Improve paths tab size and layout
Paths are too crowded, and long paths twist themsleves up: they should be given room to spread out.
- Default size of window can also be enlarged.
- Long paths can have the source and destination anchors set to the lower corners.
- Short paths can have the anchors set closer to the lower center.
- The link distance can also be shortened if that helps.

### PR DESCRIPTION
**Pull request by mwfarb**
- Updated anchors to spread out for complex graphs
- Shortened link distance for paths.
- Increased window size.
- Fixes #27.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-viz/33)

### CODE REVIEW

**Comment by mwfarb** [comment]
@mlegner Let me know if you have time to take a look.

**Comment by ercanucan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/web/asviz/static/js/tab-topocola.js, line 71 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/33#-KyaaW1vGGvV8ZZ8gm7C:-KyaaW1vGGvV8ZZ8gm7D:b4t10ac) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/e3c07d59c2d3fc2b4832e2138b98b5e1f67d457e/python/web/asviz/static/js/tab-topocola.js#L71)):*
> ```JavaScript
>     var min_interfaces = paths[0].length;
>     for (path in resPath.if_lists) {
>         if ((paths[path].length) < min_interfaces) {
> ```

unnecessary parentheses?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/33)*

**Comment by ercanucan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/33)*

**Comment by mwfarb** [comment]
@ercanucan Ok that settles it. I just pushed this change but since the link to my fork has been severed it won't show here. I will definitely have to redo my fork and PRs.

**Comment by mwfarb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/web/asviz/static/js/tab-topocola.js, line 71 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/33#-KyaaW1vGGvV8ZZ8gm7C:-KyasQcWeTaP3_btRJPr:b-upvpi3) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/e3c07d59c2d3fc2b4832e2138b98b5e1f67d457e/python/web/asviz/static/js/tab-topocola.js#L71)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

unnecessary parentheses?
</blockquote></details>

Removed, but I'll have to regenerate the PR/fork.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/33)*

**Comment by ercanucan** [comment]
Replaced by https://github.com/netsec-ethz/scion-viz/pull/35

**Pull request closed without merging**
