### PR TITLE
Correct legend and AS node paths color scheme (old fork)

### PR DESCRIPTION
**Pull request by mwfarb**
This fixes several inconsistencies with the display of the correct colors and labels of the legend in the AS Visualization Paths tab and corrects a corresponding issue for the Proxy Visualization Paths tab for older demos.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-viz/25)

### CODE REVIEW

**Comment by mwfarb** [comment]
@mlegner

**Comment by ercanucan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[ext/visualization/tab-topocola.js, line 18 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/25#-KyaeDC1iZCnVwIpjAgh:-KyaeDC1iZCnVwIpjAgi:b-pom7jt) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/efe78fab9cff17b2964fac05dc532e9a929eec18/ext/visualization/tab-topocola.js#L18)):*
> ```JavaScript
> 
> /*
>  * TODO (mwfarb): topology.js and tab-topocola.js are used in more then one
> ```

Maybe a good idea to create an issue for that. I think it's important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/25)*

**Comment by mwfarb** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[ext/visualization/tab-topocola.js, line 18 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/25#-KyaeDC1iZCnVwIpjAgh:-KyasbTQmDA3kgtd9LVW:bfj16f3) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/efe78fab9cff17b2964fac05dc532e9a929eec18/ext/visualization/tab-topocola.js#L18)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

Maybe a good idea to create an issue for that. I think it's important.
</blockquote></details>

I'll create a new issue, and tag it in a new PR when I refork.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/25)*

**Comment by ercanucan** [comment]
Replaced by https://github.com/netsec-ethz/scion-viz/pull/37

**Pull request closed without merging**
