### PR TITLE
Removes extra arrowhead from non-Firefox (old fork)

### PR DESCRIPTION
**Pull request by mwfarb**
- Updated to PR 24 fix.
- Removes same interface links from constructed paths.
- Effectually removes extra arrowhead at the 9pm position on ASes.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-viz/26)

### CODE REVIEW

**Comment by mwfarb** [comment]
@mlegner

**Comment by ercanucan** [comment]
:lgtm: (only one minor comment)

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/web/asviz/static/js/topology.js, line 93 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/26#-Kya_vNF_IfZf05RJh1P:-Kya_vNF_IfZf05RJh1Q:b-w5179k) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/7b1000a7a23e44606ada0002ee192e36173e08d6/python/web/asviz/static/js/topology.js#L93)):*
> ```JavaScript
>             if (isd == 0) {
>                 var core = (a.type != LinkType.Core)
>                         - (b.type != LinkType.Core);
> ```

was this change on purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/26#-:-Kyaa316g1Yq-aiscbLm:b-ijcdna)*

**Comment by ercanucan** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/26)*

**Comment by mwfarb** [comment]
Thanks! Please merge if you can.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/web/asviz/static/js/topology.js, line 93 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/26#-Kya_vNF_IfZf05RJh1P:-Kyanmq6ZV0poHwP_gd1:bp6sl4y) ([raw file](https://github.com/netsec-ethz/scion-viz/blob/7b1000a7a23e44606ada0002ee192e36173e08d6/python/web/asviz/static/js/topology.js#L93)):*
<details><summary><i>Previously, ercanucan (ercanucan) wrote…</i></summary><blockquote>

was this change on purpose?
</blockquote></details>

Sorry about that. It seems I may not have run a format on that file previously before checking in and it exceeded the line width.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-viz/26#-:-KyaoEaYWEBqGXR375b-:bfucur5)*

**Comment by ercanucan** [comment]
Replaced by https://github.com/netsec-ethz/scion-viz/pull/36

**Pull request closed without merging**
